name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - run: |
          git fetch --prune --unshallow

      - name: Echo Infomation
        run: |
          echo "event name: ${{github.event_name}}"
          echo "event action: ${{github.event.action}}"
          echo "event number: ${{github.event.number}}"
    
      - name: Get semver
        id: semver
        uses: heineiuo/get-commit-semver@main
    
      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        if: |
          github.event_name == 'push' && steps.semver.outputs.valid == 'true'
        with:
          tag: ${{ steps.semver.raw }}

      - name: Create Changelogs
        if: |
          github.event_name == 'push' && steps.semver.outputs.valid == 'true'
        id: changelog
        uses: heineiuo/create-changelogs@master

      - name: Create Release
        if: |
          github.event_name == 'push' && steps.semver.outputs.valid == 'true'
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.raw }}
          release_name: ${{ steps.semver.raw }}
          body: ${{ steps.changelog.outputs.changelog_text }}
          draft: false
          prerelease: ${{ steps.changelog.outputs.release_type == 'prerelease' }}
